
package simple.jaxws.server;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://server.jaxws.simple/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sleep", targetNamespace = "http://server.jaxws.simple/", className = "simple.jaxws.server.Sleep")
    @ResponseWrapper(localName = "sleepResponse", targetNamespace = "http://server.jaxws.simple/", className = "simple.jaxws.server.SleepResponse")
    public String sleep(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "ping", targetNamespace = "http://server.jaxws.simple/", className = "simple.jaxws.server.Ping")
    public void ping();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.jaxws.simple/", className = "simple.jaxws.server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.jaxws.simple/", className = "simple.jaxws.server.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
