
package simple.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Fri May 15 03:29:58 PDT 2020
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "say", namespace = "http://cxf.simple/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "say", namespace = "http://cxf.simple/")

public class Say {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

