
package simple.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Fri May 15 03:29:59 PDT 2020
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "sayResponse", namespace = "http://cxf.simple/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayResponse", namespace = "http://cxf.simple/")

public class SayResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

