
package simple.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2020-05-15T03:50:13.655-07:00
 * Generated source version: 2.7.9
 * 
 */
public final class HelloIF_HelloPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.simple/", "HelloService");

    private HelloIF_HelloPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
        HelloIF port = ss.getHelloPort();  
        
        {
        System.out.println("Invoking say...");
        java.lang.String _say_arg0 = "_say_arg0611093493";
        java.lang.String _say__return = port.say(_say_arg0);
        System.out.println("say.result=" + _say__return);


        }

        System.exit(0);
    }

}
